[package]
name = "ch4"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "link_ref"
path = "src/link_ref.rs"

[[bin]]
name = "slices"
path = "src/slices.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
